service: ecommerce-serverless-app-new
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs20.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1

functions:
  #authorizer function
  authorizerCustom:
    handler: src/handlers/auth/authorizer.authorizer
  #this is lambda functions that responsible of execution a piece of code
  createProduct:
    handler: src/handlers/products/createProduct.createProduct
    environment:
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1 # for using the same HTTP connection to multiple request for optimizing performance  and rpevent re-creating TCP connection for each request
    iamRoleStatements:
      - Effect: Allow 
        Action: 
          - dynamodb:PutItem
        Resource: 
          - !GetAtt productsTable.Arn
          - !GetAtt usersTable.Arn
    events:
      #http event
      - http:
          method: post
          path: products
          authorizer: authorizerCustom
  updateProduct:
    handler: src/handlers/products/updateProduct.updateProduct
    environment:
      PRODUCTS_TABLE_NAME: !Ref  productsTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
      - Effect: Allow 
        Action: 
          - dynamodb:UpdateItem
        Resource: 
          - !GetAtt productsTable.Arn
          - !GetAtt usersTable.Arn
    events:
      - http:
          method: put 
          path: product/{id}
          authorizer: authorizerCustom
  deleteProduct:
    handler: src/handlers/products/deleteProduct.deleteProduct
    environment:
      PRODUCTS_TABLE_NAME: !Ref  productsTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1 # for using the same HTTP connection to multiple request for optimizing performance  and rpevent re-creating TCP connection for each request 
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
        Resource: 
          - !GetAtt productsTable.Arn
          - !GetAtt usersTable.Arn
    events:
      - http:
          method: delete 
          path: product/{id}
          authorizer: authorizerCustom
  getAllProduct:
    handler: src/handlers/products/getAllProduct.getAllProduct
    environment:
      PRODUCTS_TABLE_NAME: !Ref  productsTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Scan
        Resource: 
          - !GetAtt productsTable.Arn
          - !GetAtt usersTable.Arn
    events:
      - http:
          method: get 
          path: product
          authorizer: authorizerCustom

plugins:
  - serverless-iam-roles-per-function

#CloudFormation Resource templates 
#-->congif for creating databasa in dynamoDB
resources:
  Resources:
    productsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: products
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: productsId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: productsId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: UserIdIndex
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH