service: ecommerce-serverless-api
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs20.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1

functions:
  createProduct:
    handler: handler.createProduct
    events:
      - http:
          method: post
          path: products
  updateProduct:
    handler: handler.updateProduct
    events:
      - http:
          method: put
          path: products/{id}
  deleteProduct:
    handler: handler.deleteProduct
    events:
      - http:
          method: delete
          path: products/{id}
  getAllProducts:
    handler: handler.getAllProducts
    events:
      - http:
          method: get
          path: products

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
