service: ecommerce-serverless-api
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs20.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1

functions:
  createProduct:
    handler: handler.createProduct
    events:
      - http:
          method: post
          path: products
  updateProduct:
    handler: handler.updateProduct
    events:
      - http:
          method: put
          path: products/{id}
  deleteProduct:
    handler: handler.deleteProduct
    events:
      - http:
          method: delete
          path: products/{id}
  getAllProducts:
    handler: handler.getAllProducts
    events:
      - http:
          method: get
          path: products 

# you can add CloudFormation resource templates here
resources:
  Resources:
    productsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: products 
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: productId
            AttributeType: S #is for string type
        KeySchema:
          - AttributeName: productId
            KeyType: HASH

